### ISSUE TITLE
Error loading RgGen::Markdown

### ISSUE THREAD

**Issue by rickselby** [rggen/rggen-markdown#30]
I'm trying to use https://github.com/sebyx07/rspec-github-actions-summary but it's failing when loading this gem.

This worked fine with the previous gems (`rggen-core 0.26`, `rggen-markdown 0.22`).

With `rggen-core 0.27`, `rggen-markdown 0.22` (previous version):

```
NameError:
  uninitialized constant RgGen::Core::Plugin
  Did you mean?  RgGen::Core::PluginError
# /bundle/ruby/2.7.0/gems/rggen-markdown-0.22.0/lib/rggen/markdown.rb:13:in `<module:Markdown>'
# /bundle/ruby/2.7.0/gems/rggen-markdown-0.22.0/lib/rggen/markdown.rb:12:in `<module:RgGen>'
# /bundle/ruby/2.7.0/gems/rggen-markdown-0.22.0/lib/rggen/markdown.rb:11:in `<top (required)>'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary/output.rb:4:in `require'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary/output.rb:4:in `<top (required)>'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary.rb:5:in `require_relative'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary.rb:5:in `<top (required)>'
# ./spec/spec_helper.rb:9:in `require'
# ./spec/spec_helper.rb:9:in `<top (required)>'
No examples found.
```

With `rggen-core 0.27`, `rggen-markdown 0.23` (current version):
```
NoMethodError:
  undefined method `setup_plugin' for nil:NilClass
# /bundle/ruby/2.7.0/gems/rggen-markdown-0.23.0/lib/rggen/markdown.rb:11:in `<top (required)>'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary/output.rb:4:in `require'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary/output.rb:4:in `<top (required)>'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary.rb:5:in `require_relative'
# /bundle/ruby/2.7.0/gems/rspec-github-actions-summary-0.1.0/lib/rspec_github_actions_summary.rb:5:in `<top (required)>'
# ./spec/spec_helper.rb:9:in `require'
# ./spec/spec_helper.rb:9:in `<top (required)>'
No examples found.

```

**Comment by taichi-ishitani** [comment]
Hi @rickselby ,

You need to add the following code before loading RgGen::Markdown.

```ruby
require 'rggen/core'
builder = RgGen::Core::Builder.create
RgGen.builder(builder)
```

----

I think you need to use `TableFormatter` only.
If yes, you only have to load following files to use this class

```ruby
require 'facets/module/attr_setter'
require 'rggen/core/utility/code_utility/line'
require 'rggen/core/utility/code_utility/code_block'
require 'rggen/core/utility/code_utility/source_file'
require 'rggen/core/utility/code_utility/structure_definition'
require 'rggen/core/utility/code_utility'
require 'rggen/markdown/utility/table_formatter'
```

**Comment by taichi-ishitani** [comment]
I've open a PR to fix this error.

sebyx07/rspec-github-actions-summary#1

**Comment by rickselby** [comment]
Thanks, that's very kind. I couldn't see a changelog or similar, so couldn't track this down. That's quite the change!

**Comment by taichi-ishitani** [comment]
I think you can prevent this error by specifying version of `rggen-core` and `rggen-markdown`.

```ruby
# Gemfile
gem 'rggen-core', '~> 0.26.0'
gem 'rggen-markdown', ' ~> 0.22.0'
```
